export const MESSAGE_TYPES = Object.freeze({
  AUDIO: "audio",
  AUDIO_FILE: "audio-file",
  AUDIO_FILE_ERROR: "audio-file-error",
  ENSURE_NATIVE: "ensure-native",
  ERROR: "error",
  HOST_READY: "host-ready",
  LOG: "log",
  OFFSCREEN_CLOSED: "offscreen-closed",
  OFFSCREEN_READY: "offscreen-ready",
  OPEN_RECORDINGS_FOLDER: "open-recordings-folder",
  OPEN_SAVED_FOLDER: "open-saved-folder",
  PING: "ping",
  RECORDING_STARTED: "recording-started",
  RECORDING_STATUS: "recording-status",
  RECORDING_STOPPED: "recording-stopped",
  REQUEST_AUDIO_PLAYBACK: "request-audio-playback",
  RESULT: "result",
  START_RECORDING: "start-recording",
  STATUS: "status",
  STOP_RECORDING: "stop-recording",
  WARN: "warn",
});

